Log error message from failed send attempts
Currently, logs show the following which is not helpful in identifying a problem with the log export.

```checkpoint: 90020190628032144798656085170094219032655730256692379730
start: 2019-06-28T03:21:51.914Z
end: 2019-06-28T03:21:57.119Z
logsProcessed: 0
error: [{"cause":{},"isOperational":true},"Skipping logs from 90020190628031540443551250646802263919691376682789240930 to 90020190628032144798656085170094219032655730256692379730 after 5 retries."]```